# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0024_auto_20170827_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenvibes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.DeleteModel(
            name='GreenVibes',
        ),
    ]
