# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0025_auto_20170916_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
