# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0026_delete_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picto',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(upload_to='media'),
        ),
    ]
