# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0027_auto_20170918_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picto',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(upload_to=b''),
        ),
    ]
